name: build module
on: 
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🧰 Setup
        uses: m4c0/ecow/.github/actions/setup@main
        with:
          os: ${{ matrix.os }}
      - name: 🧀 Prepare Deps
        uses: m4c0/hai/.github/actions/deps@main
      - name: 🔨 Build
        uses: m4c0/ecow/.github/actions/compile@main
        with:
          os: ${{ matrix.os }}
          project: hai
      - name: 🧩 Test (macosx)
        if: ${{ matrix.os == 'macos-latest' }}
        run: ./out/macosx/example.exe
        working-directory: hai
      - name: 🧩 Test (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: ./out/win32/example.exe
        working-directory: hai
